services:
  onewire:

    build:
      context: .
      dockerfile: ./Dockerfile

    image: ghcr.io/udochrist/onewire-docker:latest
    container_name: onewire
    restart: unless-stopped
        
    security_opt:
      - apparmor:unconfined

    cap_add:
      - SYS_ADMIN
      
    volumes:
      - ./config:/config

    environment:
      START_OWHTTPD: "${START_OWHTTPD:-true}"
      START_OWFS: "${START_OWFS:-false}"
    
    devices:
      - /dev/fuse:/dev/fuse:rwm
   
    ports:
      - 4304:4304 # SERVER
      - 2120:2120 # FTP
      - 2121:2121 # HTTP
