# Sample configuration file for the OWFS suite
#
#
# This configuration should be overwritten by mounting a volume.
# It simulates faked devicesfor first functional tests, because 
# owserver fails starting quiet if there is no ow-device found. 

#########################################################
# Sample configuration file for the OWFS suite for Debian GNU/Linux.
#
#
# This is the main OWFS configuration file. You should read the
# owfs.conf(5) manual page in order to understand the options listed
# here.

######################## SOURCES ########################
#
# With this setup, any client (but owserver) uses owserver on the
# local machine...
#! server: server = localhost:4304
#
# ...and owserver uses the real hardware, by default fake devices
# This part must be changed on real installation
server: FAKE = DS18S20,DS2405,DS18B20
#
# USB device: DS9490
#server: usb = all
#
# Serial port: DS9097
#server: device = /dev/ttyS1
#
######################### OWFS ##########################
# mountpoint = /mnt/1wire
# allow_other

####################### OWHTTPD #########################
http: port = 2121

####################### OWFTPD ##########################
ftp: port = 2120

####################### OWSERVER ########################
!SERVER: s 4304
SERVER: p 4304