#########################################################
# OWFS config file

######################## SOURCES ########################
server: fake = DS18S20,DS2405,DS18B20

#server: usb = all
#server: device = /dev/ttyS1

# all processes use the local server
! server: server = 4304

######################### OWFS ##########################
# mountpoint = /mnt/1wire
# allow_other

http: port = 2121
ftp: port = 2120

server: port = 4304